### PR TITLE
Add multiple options example

### PR DESCRIPTION
**Pull request by libuk**
I couldn't find an example of using multiple options in the official docs and couldn't find it here in the repo, so I thought I'd add it myself.

### CODE REVIEW

**Comment by igorescobar** [comment]
Well spotted @libuk! 
It will be improved for sure!

**Comment by igorescobar** [comment]
@jcguarinpenaranda Can you merge it, please?

**Comment by jcguarinpenaranda** [comment]
Merged! :)

**Comment by libuk** [comment]
Thanks guys! 🙌🏾

**Pull request merged**
